amazon:
  dynamodb:
    endpoint: http://localhost:8000/
  aws:
    access-key: key
    secret-key: secret
    region: sa-east-1

spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create-only